### ISSUE TITLE
JaCoCo added as a non-scoped transitive dependency

### ISSUE THREAD

**Issue by proteus-russ** [aws/aws-secretsmanager-jdbc#139]
After upgrading from 1.08 to 1.0.10 I noticed a new transitive dependency on JaCoCo.

It looks like this dependency should have a test scope.

It was introduced in #93

**Comment by benjaminkz** [comment]
Hi proteus-russ! We are using PowerMock framework for our Junit test cases. It is a known issue that JaCoCo does not work with PowerMock properly in on-the-fly instrumentation, so offline instrumentation is recommended by PowerMock instead. For offline instrumentation, instrumented classes get a direct dependency on the JaCoCo runtime. Therefore, org.jacoco.agent has to be a runtime dependency.

A few links for your reference:

- https://github.com/powermock/powermock/wiki/Code-coverage-with-JaCoCo
- https://github.com/powermock/powermock/issues/727
- https://www.jacoco.org/jacoco/trunk/doc/offline.html
