### ISSUE TITLE
Support for org.postgresql.xa.PGXADataSource

### ISSUE THREAD

**Issue by pethers** [aws/aws-secretsmanager-jdbc#16]
Have created a simple impl at https://github.com/Hack23/cia/blob/master/service.data.impl/src/main/java/com/hack23/cia/service/data/impl/util/SecretPGXADataSource.java , maybe something more people need.

**Comment by willtong1234** [comment]
Thank you for your feedback. We have noted this as a feature request.

**Comment by willtong1234** [comment]
We have reviewed the implementation and decided that it does not belong in the Secrets Manager JDBC library. It does seem useful and we will consider adding a PGXA data source in the future as a separate library. Closing out this issue, thank you for your contribution!
