### ISSUE TITLE
Connection from AWS EKS Fargate to Secrets Manager without using an AWS_ACCESS_KEY.

### ISSUE THREAD

**Issue by paulwebdevgit** [aws/aws-secretsmanager-jdbc#216]
Hi,
i am utilizing the library within my Spring Boot application, which is hosted on an AWS EKS Fargate cluster. I have assigned an IAM Role with web identity to the ServiceAccount responsible for accessing the Secret Manager for an RDS PostgreSQL database. 
However, I am encountering an error during this access attempt:

“Unable to load credentials from system settings. Access key must be specified either via environment variable (AWS_ACCESS_KEY_ID) or system property (aws.accessKeyId)."

I don't have an AWS_ACCESS_KEY_ID because I am use an IAM Role instead.

What could be the problem? Can i use the library with Fargate?

Verisons : 
implementation("com.amazonaws.secretsmanager:aws-secretsmanager-jdbc:2.0.0")
implementation("software.amazon.awssdk:sts:2.21.6")

**Comment by maciejwalkowiak** [comment]
Can you paste full stacktrace? Are you getting this exception from Secrets Manager JDBC library?

**Comment by paulwebdevgit** [comment]
Yes, of course: 
{
    "time": "2023-11-08T10:20:34.508019298Z",
    "stream": "stdout",
    "logtag": "F",
    "message": "2023-11-08T10:20:34.506Z  WARN 1 --- [           main] 
    ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Failed to initialize pool: Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long.",
    "log": "2023-11-08T10:20:34.508019298Z stdout F 2023-11-08T10:20:34.506Z  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Failed to initialize pool: Received an UnknownHostException when attempting to interact with a service. See cause for the exact endpoint that is failing to resolve. If this is happening on an endpoint that previously worked, there may be a network connectivity issue or your DNS cache could be storing endpoints for too long."
}

**Comment by maciejwalkowiak** [comment]
Ok this looks like an authentication error on the Secrets Manager JDBC library - Spring Cloud AWS does not provide any integration with it so I think you should move this issue to its repo

**Comment by paulwebdevgit** [comment]
I don't really understand what you mean. We don't use the Spring Cloud AWS in this context. Are we facing an issue related to the SecretsManager JDBC library itself or is it possibly stemming from our configurations within AWS?

**Comment by paulwebdevgit** [comment]
The error before have been resolved, but I am getting another error: 
{
    "time": "2023-11-08T14:03:50.660632462Z",
    "stream": "stdout",
    "logtag": "F",
    "message": "2023-11-08T14:03:50.660Z  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: org.postgresql.util.PSQLException: The connection attempt failed.",
    "log": "2023-11-08T14:03:50.660632462Z stdout F 2023-11-08T14:03:50.660Z  WARN 1 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: org.postgresql.util.PSQLException: The connection attempt failed."
}

**Comment by paulwebdevgit** [comment]
Is done
