### ISSUE TITLE
Cannot specify region without global AWS config

### ISSUE THREAD

**Issue by toran414** [aws/aws-secretsmanager-jdbc#27]
So this works great, but I can't find a good way to customize the secrets manager client without extending the driver or setting configuration globally.  We have applications deployed in both regions, but because of how our cloud formation scripts (Which create the DB cred secrets) work, the secret is only present in one region (Where the master is).  We use the standard auto-detection for region and role on our servers, but I need to override the region just for the SecretsManager client (Preferably just by adding a property or ENV var).

The only solution to get this working I have found is to provide the global `AWS_REGION`, but that effects other clients in the application which I don't want to change the region for.

**Comment by willtong1234** [comment]
Thank you for your feedback. We have noted this as a feature request.

**Comment by danmancuso** [comment]
We have merged #88 that adds this feature.
