### ISSUE TITLE
Load secretsmanager.properties by context instead of system classloader

### ISSUE THREAD

**Issue by martinstrejc** [aws/aws-secretsmanager-jdbc#34]
The current implementation loads secretsmanager.properties configuration by system classloader. That's a big limitation, because in server implementations system classloader is usually a bootstrap, but not a current process. In case of Tomcat it is not possible to use secretsmanager.properties file to configure secretsmanager as a datasource because system classloader is aware of few system jars only, and no way to reconfigure.

**Comment by willtong1234** [comment]
Thank you for your feedback. We have noted this as a feature request.

**Comment by MoonJongMin** [comment]
Hi, I have a same problem that ClassLoader can't find secretsmanager.properties in war application. Considering there are so many applications running based WAR, this is a very waiting feature.

**Comment by jbct** [comment]
Closing - this was merged with https://github.com/aws/aws-secretsmanager-jdbc/pull/32.
