### ISSUE TITLE
Not possible generate secretcache with aws access and secret key.

### ISSUE THREAD

**Issue by rdrmartin** [aws/aws-secretsmanager-jdbc#4]
In my application im ussing postgres driver but i need to use the constructor with AWSSecretsManager param because i connect with AWS with the access key, secret key and region.

There's any way to use this constructor specifying by configuration?

Thanks for the work.

**Comment by willtong1234** [comment]
First off, you should never hard-code the AWS access key and AWS secret key. See https://docs.aws.amazon.com/general/latest/gr/aws-access-keys-best-practices.html for AWS access key best practices. If you are running on an EC2 instance or in a Lambda, please take advantage of the instance role (for EC2) or the execution role (for Lambda). For everywhere else, follow the best practices regarding credentials files/environment variables.

Now back to your original question. The short answer is yes, this is possible. You would just deregister the existing driver and register the new driver that is instantiated with your own SDK client. For example:

```java
        // Deregister the driver first
        Enumeration<Driver> drivers = DriverManager.getDrivers();
        if (drivers != null) {
            while (drivers.hasMoreElements()) {
                Driver driver = drivers.nextElement();
                if (driver.getClass() == AWSSecretsManagerPostgreSQLDriver.class) {
                    DriverManager.deregisterDriver(driver);
                }
            }
        }

        // Register new driver
        AWSSecretsManager client = AWSSecretsManagerClientBuilder.standard()
                                       .withRegion(Regions.US_EAST_2)
                                       .build();
        DriverManager.registerDriver(new AWSSecretsManagerPostgreSQLDriver(client));
```

Hope that answers your question.

**Comment by willtong1234** [comment]
It has been 3 weeks so I'm assuming your question was answered. I'm going to resolve this issue.

**Comment by r-jindal** [comment]
Is this the only solution for the work-around ?
The solution provided is 2 years back, Is there any update on this ?
AWSSecretsManagerPostgreSQLDriver is a final class, so I cant extend that.
But there are constructors which take parameters like AWSSecretsManager client. I need to know the way, how to use them.
