### ISSUE TITLE
NPE if secret is missing username or password

### ISSUE THREAD

**Issue by kuldarisakannu** [aws/aws-secretsmanager-jdbc#45]
If the secret gets overwritten incompletely (in our case missing username) then retry results in NullPointerException at
https://github.com/aws/aws-secretsmanager-jdbc/blob/master/src/main/java/com/amazonaws/secretsmanager/sql/AWSSecretsManagerDriver.java#L325

**Comment by willtong1234** [comment]
Thank you for opening this issue - we are looking into it.

**Comment by kendrabach** [comment]
@kuldarisakannu we appreciate you bringing this to our attention. #157 contains the bug fix and has been merged.
