### ISSUE TITLE
False positive RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE

### ISSUE THREAD

**Issue by royandrew** [aws/aws-secretsmanager-jdbc#63]
Findbug plugin generates false positive RCN_REDUNDANT_NULLCHECK_OF_NONNULL_VALUE for Config.loadPropertiesFromConfigFile method. Updating the plugin to spotbugs should fix the issue.

**Comment by simonmarty** [comment]
Fixed in #68
